[package]
name = "nut_self"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"
repository = "https://github.com/yusdacra/nut_self"
license = "MIT"

[lib]
proc-macro = true

[workspace]
members = ["example"]

[dependencies]